export const EDUCATION = [
  {
    id: 1,
    name: "United International University",
    location: "Dhaka, Bangladesh",
    degree: "Bachelor of Science in Computer Science & Engineering",
    cgpa: "3.43 out of 4.00",
    duration: "January, 2020 - October, 2024",
  },
  {
    id: 2,
    name: "B.A.F Shaheen College Kurmitolla",
    location: "Dhaka, Bangladesh",
    degree: "Higher Secondary School Ceritificate",
    cgpa: "4.92 out of 5.00",
    duration: "2017 - 2019",
  },
];
